---

- name: Permissions | Change owner and group of Magento source
  file: path={{ magento_src_dir }}
        owner={{ magento_application_user }} group=www-data state=directory recurse=yes

- name: Permissions | Give All Magento files 644 permission
  command: find {{ magento_src_dir }} -type f -exec chmod 644 {} \;

- name: Permissions | Give all Magento folders 755 permission
  command: find {{ magento_src_dir }} -type d -exec chmod 755 {} \;

- name: Permissions | Ensure the owner can write to these directories
  command: chmod g+w {{ item }}
  with_items:
    - '{{ magento_src_dir }}/app/etc'
    - '{{ magento_src_dir }}/var'

- name: Permissions | Change ownership of Magento installation 5
  file: path={{ magento_src_dir }}/mage mode=550

- name: Permissions | Change ownership of Magento installation 6
  command: chmod -R g+w {{ magento_media_dir }}

- name: Permissions | ensure group can write to Magento source
  command: chmod -R g+rw {{ magento_src_dir }}
