---

- name: Users & Accounts | Add application group
  group: name={{ magento_application_group }} system=yes state=present

- name: Users & Accounts | Ensure web folder is made before we add our user
  file: path=/var/www state=directory owner='www-data' group='www-data'

- name: Users & Accounts | Add application user
  user: name={{ magento_application_user }} group={{ magento_application_group }} state=present
        createhome=yes home={{magento_home_dir }} shell=/bin/bash system=true

- name: Users & Accounts | Grant application user sudo access
  copy: content='{{ magento_application_user }} ALL=(ALL) NOPASSWD:ALL'
        dest=/etc/sudoers.d/magento_application_user mode=0440

- name: Users & Accounts | Ensure storage directory is made
  file: path={{ magento_storage_dir }} state=directory
        owner={{ magento_application_user }} group='www-data'

- name: Users & Accounts | Ensure media directory is made
  file: path={{ magento_media_dir }} state=directory
        owner={{ magento_application_user }} group='www-data'

- name: Users & Accounts | Add key to authorized keys
  authorized_key: user={{ magento_application_user }} key="{{ magento_public_key }}"

- name: Users & Accounts | Set application environmental variables
  template: src=bash_profile.j2 dest={{magento_home_dir }}/.bash_profile
            owner={{ magento_application_user }} group={{ magento_application_user }}
  tags:
    - env

- name: Users & Accounts | Create the applications releases Folder
  file: path={{ magento_release_dir }} state=directory
        owner={{ magento_application_user }} group='www-data'
